### ISSUE TITLE
Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by nissoh** [TylorS/reginn#7]
Hey @TylorS, thank you for this project.

i've got `cli.ts` file

````typescript
import { command, app, flag, alias, withPromise, run, withCallback } from 'reginn'


const logcmd = command(alias('justlog'))

withPromise(logcmd)
  .then(({ args }) => {
    console.log('fff')
  })

run(logcmd)
````

running `ts-node ./cli.ts justlog` will result this error

````
TypeError: Cannot read property 'flags' of undefined
    at Object.run (/Users/hanni05/GIT/mostly-dom/node_modules/reginn/src/run/run.ts:30:55)
    at Object.<anonymous> (/Users/hanni05/GIT/mostly-dom/cli.ts:20:1)
    at Module._compile (module.js:570:32)
    at Module.m._compile (/Users/hanni05/.nvm/versions/node/v6.9.1/lib/node_modules/ts-node/src/index.ts:406:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/hanni05/.nvm/versions/node/v6.9.1/lib/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
````

trying to wrap my head around the reason this won't work i tried to read and reread the documentation without any idea what am i doing wrong.

i tried to install 1.0.4 version and tried the same thing with `.asPromise` method. and it seemed to work as expected.

**Comment by TylorS** [comment]
Hello @nissoh, thanks for trying out Reginn. Just to see if we can narrow the issue down a bit, does switching the last line to 
```typescript
run(process.argv.slice(2), logcmd)
```

fix your issue?

**Comment by nissoh** [comment]
`run([], logcmd)` or `run(process.argv.slice(2), logcmd)` the `command.flags` null point exception is gone.

`justlog` is being executed even if we did not specify the `justlog` argument

i.e. `ts-node ./cli.ts yoho`  will run `justlog` command

**Comment by nissoh** [comment]
logging process.argv.slice(2) will result in empty array O_o

**Comment by TylorS** [comment]
Hey @nissoh, your original code snippet should work with v2.1.5, just released, tried it myself. Let me know if it's working :)

**Comment by TylorS** [comment]
Relevant commit is [here](https://github.com/TylorS/reginn/commit/882a91c95067895e32b13c4caeff3cd9734e9b79)

**Comment by nissoh** [comment]
Yay (:

**Comment by TylorS** [comment]
Thanks for the issue, and I hope the library works well for you! :)
